###
GET http://localhost:4040/user/ HTTP/1.1

###
POST http://localhost:4040/user/registrar HTTP/1.1
Content-Type:application/json

{
    "name": "ingrid paola",
    "lastName": "jimenez robles",
    "age": 25,
    "email": "ingrid@hotmail.com",
    "password": "admin123"
}

###
POST http://localhost:4040/login/ HTTP/1.1
Content-Type:application/json

{
    "email": "ingrid@hotmail.com",
    "password": "admin123"
}
###
POST http://localhost:4040/product/createProduct HTTP/1.1
Content-Type:application/json

{
    "url": "urltest",
    "name": "pizza",
    "price": 15000,
    "qualification" : 0,
    "postedBy": "marlon"
}
